MyAppointments/CancelAppointment/ReentryAppointment
develop-dmitry/hospital pull request #10
Opened 2023-04-13 19:20 UTC by samirtula

2023-04-14 18:49 UTC, develop-dmitry requested changes

2023-04-14 18:49 UTC, develop-dmitry commented on database/migrations/2023_04_13_181333_add_canceled_to_appointments_table.php
> +        Schema::table('appointments', function (Blueprint $table) {
Дописать down метод

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/ReentryAppointmentMessangerHandler.php
> +    {
Открывающая скобка на строку выше

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/ReentryAppointmentMessangerHandler.php
> +    {
Открывающая скобка на строку выше

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/MyAppointmentMessangerHandler.php
> +    {
Скобочку выше

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/MyAppointmentMessangerHandler.php
> +    {
Скобочку выше

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/ReentryAppointmentMessangerHandler.php
> +class ReentryAppointmentMessangerHandler implements MessangerHandlerInterface
ReMakeAppointmentHandler

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/AppointmentMessangerHandler.php
> +            $messanger->setMessage('У вас отсутствуют активные записи');
Сделать проверку $appointments и при отстуствии данных выйти из скрипта

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/CancelAppointmentMessangerHandler.php
> +            $messanger->editMessage();
Вынести editMessage за try/catch

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/MyAppointmentMessangerHandler.php
> +class MyAppointmentMessangerHandler implements MessangerHandlerInterface
Переименовать класс AppointmentMenuMessangerHandler

2023-04-14 18:49 UTC, develop-dmitry commented on app/Hospital/Application/Messanger/MessangerHandler/AppointmentMessangerHandler.php
> +class AppointmentMessangerHandler implements MessangerHandlerInterface
Переименовать класс AppointmentListMessangerHandler

2023-04-14 19:22 UTC, samirtula commented on app/Hospital/Application/Messanger/MessangerHandler/MyAppointmentMessangerHandler.php
> +class MyAppointmentMessangerHandler implements MessangerHandlerInterface
+

2023-04-14 19:29 UTC, samirtula commented on app/Hospital/Application/Messanger/MessangerHandler/CancelAppointmentMessangerHandler.php
> +            $messanger->editMessage();
+

2023-04-14 19:31 UTC, samirtula commented on app/Hospital/Application/Messanger/MessangerHandler/AppointmentMessangerHandler.php
> +            $messanger->setMessage('У вас отсутствуют активные записи');
+

2023-04-14 19:31 UTC, samirtula commented on app/Hospital/Application/Messanger/MessangerHandler/ReentryAppointmentMessangerHandler.php
> +class ReentryAppointmentMessangerHandler implements MessangerHandlerInterface
+

2023-04-14 19:32 UTC, samirtula commented on app/Hospital/Application/Messanger/MessangerHandler/MyAppointmentMessangerHandler.php
> +    {
+

2023-04-14 19:32 UTC, samirtula commented on app/Hospital/Application/Messanger/MessangerHandler/MyAppointmentMessangerHandler.php
> +    {
+

2023-04-14 19:32 UTC, samirtula commented on app/Hospital/Application/Messanger/MessangerHandler/ReentryAppointmentMessangerHandler.php
> +    {
+

2023-04-14 19:32 UTC, samirtula commented on app/Hospital/Application/Messanger/MessangerHandler/ReentryAppointmentMessangerHandler.php
> +    {
+

2023-04-14 20:48 UTC, samirtula commented on database/migrations/2023_04_13_181333_add_canceled_to_appointments_table.php
> +        Schema::table('appointments', function (Blueprint $table) {
+

2023-04-15 08:32 UTC, develop-dmitry approved these changes

2023-04-15 08:45 UTC, merged